xsafe:        false
port:       4000
base-url:    /


source:      .
destination: ./_site
plugins_dir:     ./_plugins

#General
name: Ron Alleva's Blog
description: "I currently software all day for <a href='http://accolade.com'>Accolade</a>"


paginate: 5

# Social share and comments.
disqus-id: ronnie76erblog
twitter: Ronnie76er
github: Ronnie76er
google: +RonAlleva

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
encoding:    utf-8
permalink:   date

rdiscount:
  extensions: []

gems: [jekyll-paginate]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style


